export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'USERS_LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'USERS_LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'USERS_LOGOUT_FAILURE';

export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const CATEGORY_PAGE_REQUEST = 'CATEGORY_PAGE_REQUEST';
export const CATEGORY_PAGE_SUCCESS = 'CATEGORY_PAGE_SUCCESS';
export const CATEGORY_PAGE_FAILURE = 'CATEGORY_PAGE_FAILURE';

// category create
export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAILURE = 'CATEGORY_CREATE_FAILURE';

// category update
export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAILURE = 'CATEGORY_UPDATE_FAILURE';

// category delete
export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAILURE = 'CATEGORY_DELETE_FAILURE';

export const TOGGLE_CREATE_PRODUCT_FORM = 'TOGGLE_CREATE_PRODUCT_FORM';
export const TOGGLE_EDIT_PRODUCT_FORM = 'TOGGLE_EDIT_PRODUCT_FORM';
export const TOGGLE_CREATE_CATEGORY_FORM = 'TOGGLE_CREATE_CATEGORY_FORM';
export const TOGGLE_EDIT_CATEGORY_FORM = 'TOGGLE_EDIT_CATEGORY_FORM';

// select category
export const MARK_CATEGORY = 'MARK_CATEGORY';

// product page
export const PRODUCT_PAGE_REQUEST = 'PRODUCT_PAGE_REQUEST';
export const PRODUCT_PAGE_SUCCESS = 'PRODUCT_PAGE_SUCCESS';
export const PRODUCT_PAGE_FAILURE = 'PRODUCT_PAGE_FAILURE';

// product create
export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAILURE = 'PRODUCT_CREATE_FAILURE';

// product update
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILURE = 'PRODUCT_UPDATE_FAILURE';

// product delete
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE';

// select product
export const MARK_PRODUCT = 'MARK_PRODUCT';
